# Generated by Django 5.1.1 on 2025-07-23 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('specializations', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('working_hours', models.JSONField(default=dict)),
                ('contact_preferences', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('overall_rating', models.FloatField(default=0.0)),
                ('total_completed_sessions', models.IntegerField(default=0)),
                ('total_reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accountant Profile',
                'verbose_name_plural': 'Accountant Profiles',
                'db_table': 'Accountant_profile',
            },
        ),
    ]
