# Generated by Django 5.1.1 on 2025-09-07 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_accountantprofile_profile_picture_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountantprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='contact_preferences',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='total_completed_sessions',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='total_reviews_count',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/accountants/attachments/'),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accountantprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/accountants/'),
        ),
        migrations.AlterModelTable(
            name='accountantprofile',
            table='accountant_profiles',
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/academics/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='documents/academics/attachments')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Profile',
                'verbose_name_plural': 'Academic Profiles',
                'db_table': 'academic_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/clients/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('activity_type', models.CharField(blank=True, max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='documents/clients/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'client_profiles',
            },
        ),
    ]
