# Generated by Django 5.1.1 on 2025-09-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_id_accountantprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/academics/attachments/'),
        ),
    ]
