# Generated by Django 5.1.1 on 2025-09-18 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_user_id_academicprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprofile',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='academicprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='attachments',
        ),
        migrations.CreateModel(
            name='ProfileAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='profile_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_attachments', to='profiles.academicprofile')),
                ('accountant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_attachments', to='profiles.accountantprofile')),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_attachments', to='profiles.clientprofile')),
            ],
            options={
                'verbose_name': 'Profile Attachment',
                'verbose_name_plural': 'Profile Attachments',
                'db_table': 'profile_attachments',
            },
        ),
    ]
