# Generated by Django 5.1.1 on 2025-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_academicprofile_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountantprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='accountantprofile',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
