# Generated by Django 5.1.1 on 2025-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_accountantprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
