from django.urls import path
from .views import (
    AvailableUserListAPIView,
    GroupChatRoomRetrieveUpdateDeleteAPIView,
    GroupChatRoomListAPIView,
    DirectMessageRoomListAPIView,
    DirectMessageRoomAPIView,
    RoomMessageListAPIView,
    RoomMemberListAPIView,
    GroupChatRoomCreateAPIView,
    ChatRoomAddMemberAPIView,
    ChatRoomRemoveMemberAPIView,
    ChatMessageDeleteAPIView,
    ChatMessageUpdateAPIView,
    ChatFileUploadAPIView,
    UnreadMessageCountAPIView,
    RoomMembersCountAPIView,
    MarkRoomAsReadAPIView,
)

urlpatterns = [
    path(
        "available_users/", AvailableUserListAPIView.as_view(), name="available_users"
    ),
    path(
        "chatrooms/group/",
        GroupChatRoomListAPIView.as_view(),
        name="group_chatroom_list",
    ),
    path(
        "chatrooms/group/create/",
        GroupChatRoomCreateAPIView.as_view(),
        name="create_group_chat_room",
    ),
    path(
        "chatrooms/<uuid:room_id>/",
        GroupChatRoomRetrieveUpdateDeleteAPIView.as_view(),
        name="chatroom_detail",
    ),
    path(
        "chatrooms/group/<uuid:room_id>/add_member/",
        ChatRoomAddMemberAPIView.as_view(),
        name="add_member_to_group_chat_room",
    ),
    path(
        "chatrooms/group/<uuid:room_id>/remove_member/<uuid:user_id_to_remove>/",
        ChatRoomRemoveMemberAPIView.as_view(),
        name="remove_member_from_group_chat_room",
    ),
    path(
        "chatrooms/<uuid:room_id>/messages/",
        RoomMessageListAPIView.as_view(),
        name="room_messages",
    ),
    path(
        "chatrooms/<uuid:room_id>/members/",
        RoomMemberListAPIView.as_view(),
        name="room_member_list",
    ),
    path(
        "chatrooms/direct/me/",
        DirectMessageRoomListAPIView.as_view(),
        name="direct_message_room_list",
    ),
    path(
        # getting or fetching direct message room
        "chatrooms/direct/",
        DirectMessageRoomAPIView.as_view(),
        name="create_direct_message_room",
    ),
    path(
        "chatrooms/messages/<uuid:message_id>/delete/",
        ChatMessageDeleteAPIView.as_view(),
        name="delete_chat_message",
    ),
    path(
        "chatrooms/messages/<uuid:message_id>/update/",
        ChatMessageUpdateAPIView.as_view(),
        name="update_chat_message",
    ),
    path("rooms/<uuid:room_id>/upload_file/", ChatFileUploadAPIView.as_view()),
    path("unread-count/", UnreadMessageCountAPIView.as_view(), name="unread_count"),
    path(
        "rooms/<uuid:room_id>/members/count/",
        RoomMembersCountAPIView.as_view(),
        name="room_members_count",
    ),
    path(
        "rooms/<uuid:room_id>/mark-read/",
        MarkRoomAsReadAPIView.as_view(),
        name="mark_room_read",
    ),
]
