# Generated by Django 5.1.1 on 2025-07-23 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('tax_preparation', 'Tax Preparation'), ('bookkeeping', 'Bookkeeping'), ('financial_consulting', 'Financial Consulting'), ('audit', 'Audit'), ('payroll', 'Payroll'), ('business_setup', 'Business Setup'), ('other', 'Other')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accountant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
            },
        ),
    ]
