# Generated by Django 5.1.1 on 2025-08-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_recreate_service_model'),
    ]

    operations = [
    ]
