# Generated by Django 5.1.1 on 2025-08-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20250804_1209'),
        ('services', '0004_populate_service_categories'),
    ]

    operations = [
    ]
