# Generated by Django 5.1.1 on 2025-08-07 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_merge_20250804_1211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='can_be_discussed',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='availability_notes',
            new_name='requirements_notes',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_location',
        ),
        migrations.AddField(
            model_name='service',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='experience_level_required',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert'), ('any', 'Any Level')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='location_preference',
            field=models.CharField(choices=[('online', 'Online'), ('client_office', "Client's Office"), ('my_office', 'My Office'), ('flexible', 'Flexible'), ('to_be_discussed', 'To Be Discussed')], default='online', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='price_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('needed', 'Service Needed'), ('offered', 'Service Offered')], default='needed', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='skills_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AddField(
            model_name='service',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='services_service_6d9417_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['user', 'service_type'], name='services_user_id_d592b0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'service_type'], name='services_categor_8cc090_idx'),
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
