# Generated by Django 5.1.1 on 2025-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='service_attachments/'),
        ),
    ]
