# Generated by Django 5.1.1 on 2025-09-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='services_categor_8cc090_idx',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_default',
            field=models.BooleanField(default=False, help_text='True for admin-created categories, False for user-created'),
        ),
    ]
