# Generated by Django 5.1.1 on 2025-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_service_services_categor_8cc090_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='service',
            name='experience_level_required',
        ),
        migrations.RemoveField(
            model_name='service',
            name='location_preference',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_negotiable',
        ),
        migrations.RemoveField(
            model_name='service',
            name='skills_keywords',
        ),
        migrations.RemoveField(
            model_name='service',
            name='urgency_level',
        ),
        migrations.AddField(
            model_name='service',
            name='conditions_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of conditions and requirements'),
        ),
        migrations.AddField(
            model_name='service',
            name='location_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price_description',
            field=models.TextField(blank=True, help_text='Additional details about pricing'),
        ),
        migrations.AddField(
            model_name='service',
            name='tasks_and_responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks and responsibilities'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouira'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Algiers'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', "El M'Ghair"), ('50', 'El Meniaa'), ('51', 'Ouled Djellal'), ('52', 'Bordj Badji Mokhtar'), ('53', 'Béni Abbès'), ('54', 'Timimoun'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'In Salah'), ('58', 'In Guezzam')], max_length=3, null=True),
        ),
    ]
