# Generated by Django 5.1.1 on 2025-09-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_service_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='requirements_notes',
            new_name='estimated_duration_description',
        ),
        migrations.AlterField(
            model_name='service',
            name='conditions_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='tasks_and_responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
