# Generated by Django 5.1.1 on 2025-09-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_rename_requirements_notes_service_estimated_duration_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='is_default',
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_method',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', help_text='How the service will be delivered', max_length=20),
        ),
    ]
