# Generated by Django 5.1.1 on 2025-09-17 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_servicecategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='service_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attachments', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Attachment',
                'verbose_name_plural': 'Service Attachments',
                'db_table': 'service_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
