# Generated by Django 5.1.1 on 2025-09-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_serviceattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='attachments',
        ),
    ]
