# Generated by Django 5.1.1 on 2025-10-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_service_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
    ]
