# Generated by Django 5.1.1 on 2025-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatrooms_creator_chatrooms_is_dm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
