# Generated by Django 5.1.1 on 2025-08-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmembers_user_id_alter_chatrooms_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
