# Generated by Django 5.1.1 on 2025-08-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_sender_id_chatmessages_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='room_id',
            new_name='room',
        ),
    ]
