# Generated by Django 5.1.1 on 2025-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_room_id_chatmessages_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
