# Generated by Django 5.1.1 on 2025-09-02 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessages_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.CreateModel(
            name='UserRoomLastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_last_seen', to='chat.chatrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_last_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Room Last Seen',
                'verbose_name_plural': 'User Room Last Seen',
                'db_table': 'user_room_last_seen',
                'unique_together': {('user', 'room')},
            },
        ),
    ]
