# Generated by Django 5.1.1 on 2025-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_emailverificationotp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
