# Generated by Django 5.1.1 on 2025-08-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('accountant', 'Accountant'), ('academic', 'Academic'), ('admin', 'Admin')], default='client', max_length=50),
        ),
    ]
