# Generated by Django 5.1.1 on 2025-08-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('services', '0005_merge_20250804_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
    ]
