# Generated by Django 5.1.1 on 2025-08-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='accountant_id',
            new_name='accountant',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_id',
            new_name='service',
        ),
    ]
