# Generated by Django 5.1.1 on 2025-08-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_accountant_id_booking_accountant_and_more'),
        ('services', '0007_alter_service_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proposal_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('in_person', 'In Person'), ('phone', 'Phone')], default='online', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
