# Generated by Django 5.1.1 on 2025-08-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_proposal_message_alter_booking_meeting_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
