# Generated by Django 5.1.1 on 2025-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_agreed_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='agreed_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='proposal_message',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_start',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='إضافات', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cv_file',
            field=models.FileField(blank=True, help_text='أضف السيرة الذاتية', null=True, upload_to='booking_cvs/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(default='amine aiba', help_text='الاسم الكامل', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='رابط لينكدان', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
