# Generated by Django 5.1.1 on 2025-10-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_options_remove_booking_agreed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='booking_cvs/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
